name: release and push to central

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.5"

      - name: Build binary
        env:
          GOOS: linux
          GOARCH: amd64
          VERSION: ${{ github.ref_name }}
        run: |
          make build-release

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . -t epos/epos-plugin-populator:${{ github.ref_name }}
          docker build . -t epos/epos-plugin-populator:latest
          docker push epos/epos-plugin-populator:${{ github.ref_name }}
          docker push epos/epos-plugin-populator:latest
